### ISSUE TITLE
Extend thoth-loader to handle L'Harmattan OA import

### ISSUE THREAD

**Issue by brendan-oconnell** [thoth-pub/thoth-loader#11]
Create a new loader for Thoth for bulk ingest of L'Harmattan OA book metadata from CSV.

- [x] Create metadata mapping from CSV fields to Thoth metadata fields
- [x] Create loader
- [x] Test ingest locally, check over created records, fix/iterate if required
- [x] Submit draft PR for loader
- [x] Make changes based on PR and resubmit
- [x] Run live import (including preparation e.g. backup of existing data if required)

**Comment by ja573** [comment]
> @ja573 I had this as an issue for thoth, rather than thoth-loader, so that it could appear on the general Thoth project board https://github.com/thoth-pub/thoth/projects/1 that we're using for project management. Could we move it back to thoth, even though it's not strictly a Thoth issue?

Don't worry about that – we're going to start using the new version of projects, which supports handling issues from various repositories
